### ISSUE TITLE
TCP flow is prematurely removed from conntrack

### ISSUE THREAD

**Issue by garo** [projectcalico/felix#1966]
In some cases Felix removes the conntrack entry for a TCP flow which is still active.

## Problem Description
I'm running an application as a pod which opens a TCP connection to another host. The client and server exchanges bunch of data in the beginning of the session and then the server starts to process a request for a few minutes.

During this time the TCP connection is kept open, but no data is exchanged. In some cases it seems that calico/node removes the conntrack entry for this particular TCP flow.

In the following logs the ip 10.107.137.39 is the pod ip and 10.107.136.65 is the host ip.

When using "conntrack -E -o timestamp,extended" I can see that the flow is removed from the conntrack table:

```
# Normal TCP session start
[08:20:12]	    [NEW] ipv4     2 tcp      6 120 SYN_SENT src=10.107.137.39 dst=10.1.101.223 sport=43286 dport=5433 [UNREPLIED] src=10.1.101.223 dst=10.107.136.65 sport=5433 dport=43286
[08:20:12]	 [UPDATE] ipv4     2 tcp      6 60 SYN_RECV src=10.107.137.39 dst=10.1.101.223 sport=43286 dport=5433 src=10.1.101.223 dst=10.107.136.65 sport=5433 dport=43286
[08:20:12]	 [UPDATE] ipv4     2 tcp      6 86400 ESTABLISHED src=10.107.137.39 dst=10.1.101.223 sport=43286 dport=5433 src=10.1.101.223 dst=10.107.136.65 sport=5433 dport=43286 [ASSURED]

# This is the moment when the flow is removed.
[08:21:05]	[DESTROY] ipv4     2 tcp      6 src=10.107.137.39 dst=10.1.101.223 sport=43286 dport=5433 src=10.1.101.223 dst=10.107.136.65 sport=5433 dport=43286 [ASSURED]
```

I have proven using strace that the client application doesn't close the socket. It just sits waiting for new data. I have also proven using tcpdump from the client side that no packets are exchanged when the flow is removed from the Linux kernel conntrack table.

At the same moment the calico/node logs shows a line "Removing conntrack flows ip=10.107.137.39", so this seems that I'm on the right track.

Here's a relevant log snippet from calico node. It seems that there is another pod being deleted at the same time and this incorrectly triggers Felix to delete incorrect flow from conntrack.

```
08:21:05.321 calc_graph.go 359: Local endpoint deleted id=WorkloadEndpoint(node=ip-10-107-136-65.ec2.internal, orchestrator=k8s, workload=azkaban/something-else, name=eth0)
08:21:05.321 int_dataplane.go 611: Received *proto.WorkloadEndpointRemove update from calculation graph msg=id:<orchestrator_id:"k8s" workload_id:"azkaban/something-else" endpoint_id:"eth0" > 
08:21:05.321 int_dataplane.go 733: Applying dataplane updates
08:21:05.321 endpoint_mgr.go 486: Workload removed, deleting its chains. id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"azkaban/something-else", EndpointId:"eth0"}
08:21:05.322 table.go 422: Queing deletion of chain. chainName="cali-tw-eni7a5ece1e73e" ipVersion=0x4 table="filter"
08:21:05.322 table.go 717: Invalidating dataplane cache ipVersion=0x4 reason="chain removal" table="filter"
08:21:05.322 table.go 422: Queing deletion of chain. chainName="cali-fw-eni7a5ece1e73e" ipVersion=0x4 table="filter"
08:21:05.322 endpoint_mgr.go 492: Workload removed, deleting old state. id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"azkaban/something-else", EndpointId:"eth0"}
08:21:05.322 table.go 398: Queueing update of chain. chainName="cali-from-wl-dispatch" ipVersion=0x4 table="filter"
08:21:05.323 table.go 398: Queueing update of chain. chainName="cali-to-wl-dispatch" ipVersion=0x4 table="filter"
08:21:05.323 endpoint_mgr.go 350: Re-evaluated workload endpoint status adminUp=false failed=false known=false operUp=false status="" workloadEndpointID=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"azkaban/something-else", EndpointId:"eth0"}
08:21:05.323 status_combiner.go 58: Storing endpoint status update ipVersion=0x4 status="" workload=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"azkaban/something-else", EndpointId:"eth0"}
08:21:05.323 route_table.go 557: Failed to access interface because it doesn't exist. error=Link not found ifaceName="eni7a5ece1e73e" ipVersion=0x4
08:21:05.323 table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table="filter"
08:21:05.323 route_table.go 403: Failed to get interface; it's down/gone. error=Link not found ifaceName="eni7a5ece1e73e" ipVersion=0x4
08:21:05.323 route_table.go 292: Interface missing, will retry if it appears. ifaceName="eni7a5ece1e73e" ipVersion=0x4
08:21:05.323 conntrack.go 78: Removing conntrack flows ip=10.107.137.39
08:21:05.335 status_combiner.go 86: Reporting endpoint removed. id=proto.WorkloadEndpointID{OrchestratorId:"k8s", WorkloadId:"azkaban/something-else", EndpointId:"eth0"}
08:21:05.335 int_dataplane.go 747: Finished applying updates to dataplane. msecToApply=13.105841999999999
```

## Your Environment

* Running EKS 1.11 eks.1
* Calico v3.1.3 (quay.io/calico/node:v3.1.3), installed using this guide https://docs.aws.amazon.com/eks/latest/userguide/calico.html
* Official AWS EKS ami: amazon-eks-node-1.11-v20190211 (ami-0c5b63ec54dd3fc38)

**Comment by fasaxc** [comment]
The log indicates that Felix thinks the target pod was deleted, so it removed the conntrack entries associated with it.  I think we need to investigate further:

- Are you sure the pod wasn't deleted; e.g. by a failed readiness check or because the command it was running finished?
- If you're absolutely sure it wasn't deleted, we need to investigate why Felix thought it was.

**Comment by garo** [comment]
@fasaxc Thanks for the input. I actually modified my original posting a bit because I had an incorrect log entry in the later snippet. I also modified the entries to have easier to read timestamps. Can you please check that you read the logs after my edit?

To answer your question: Yes, I am sure that the pod creating this TCP session is not dead. It also doesn't have any readiness probe configured.

**Comment by fasaxc** [comment]
Do you have the same IP assigned to multiple pods?

**Comment by garo** [comment]
I went over my logs again from a longer period and I got an idea: The "azkaban/something-else" pod was running in the same node just a few minutes before my problematic pod **and it had the same ip**.

So can this mean that calico did not realise that the something-else pod had died before the new pod was scheduled? This would fit with the fact that it is much easier for me to reproduce this issue during the morning hours when my cluster is under high usage with a lot of small pods.

I'm using the EKS CNI plugin which reuses the pod ips.

**Comment by fasaxc** [comment]
Yes, that fits with the log above.  In that mode, felix is listening for events from the API server for pod deletions (or removal of the IP from the pod).  Under load, notifications can be delayed slightly but it's unusual to see them take 10s of seconds.  Perhaps your API server or kubelet is starved for resources and it's having to batch up updates?

The Calico CNI plugin round-robbins IPs to reduce the impact of any notification latency.  Probably explains why we don't see that issue even under our churn tests.

**Comment by garo** [comment]
I'm taking a deeper look on the calico logs and in this case it seems that the  "azkaban/something-else" was started 07:18 and its execution took just ~8 seconds. However the cleanup message was not executed until 08:21:05.

Can I send you the more detailed and full felix log via email?

**Comment by fasaxc** [comment]
Easiest way is probably to get on our slack and send me the file that way.

That said, I expect the problem lies outside Felix. I'm wondering if there's something odd about the 
"azkaban/something-else" pod.  You said you have a lot of short-lived pods, are they controlled by some sort of operator; maybe there's a finalizer that's stopping the GC of the pod until long after the container has been torn down and the IP released.

If you're able to track down one of these "zombie" pods that Felix thinks is real but has long-since completed, that'd be useful.  Does it still appear in the `kubectl get pod` output?  What state is it in?

**Comment by fasaxc** [comment]
Another approach is to dig into the kubelet log; if you crank its log level up to `-v=5` then you should get logs from the CNI plugin.  Also, I think the AWS CNI plugin has its own log files that you can enable.  I'd search those for entries relating to the shared IP and the old pod.

**Comment by garo** [comment]
Thanks for the recommendations!

I will provide new set log relevant logs with more debugging from AWS CNI plugin, felix and kubelet.

I have also upgraded the AWS CNI plugin from v1.2.1 to v1.3.2 which as at least one promising change: https://github.com/aws/amazon-vpc-cni-k8s/pull/228

**Comment by fasaxc** [comment]
Should be fixed by this update: 163b5db70b8b75437a61f28bb5ee2d54af916bac

**Comment by garo** [comment]
I found our that the kubelet prints the following logs just at the same moment as when Felix deletes the conntrack entries incorrectly:

```
I0305 04:03:11.423023    5193 kubelet.go:1853] SyncLoop (DELETE, "api"): "garo-test-su67jxre2ia_azkaban(ce4cfb0f-3ef2-11e9-86fe-0ed827c0489e)"
I0305 04:03:11.423119    5193 status_manager.go:375] Status Manager: adding pod: "ce4cfb0f-3ef2-11e9-86fe-0ed827c0489e", with status: ('\x04', {Succeeded [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2019-03-05 03:00:17 +0000 UTC PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2019-03-05 03:01:20 +0000 UTC PodCompleted } {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2019-03-05 03:00:17 +0000 UTC  }]    10.107.136.65 10.107.137.216 2019-03-05 03:00:17 +0000 UTC [] [{garo-test-xxx {nil nil &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:,Message:,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} {nil nil nil} false 0 /analytics/garo_xxx:latest docker-pullable:///analytics/garo_xxx@sha256:aba5fa93509510d50c6a93cf60a679389fe2e0f67c8fa9e50557e420a65645db docker://1ae2d1f2880b4352cc438caef9286a1a1c9b9a887fd492471c37ca31d4281d34}] BestEffort}) to podStatusChannel
I0305 04:03:11.423197    5193 status_manager.go:158] Status Manager: syncing pod: "ce4cfb0f-3ef2-11e9-86fe-0ed827c0489e", with status: (4, {Succeeded [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2019-03-05 03:00:17 +0000 UTC PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2019-03-05 03:01:20 +0000 UTC PodCompleted } {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2019-03-05 03:00:17 +0000 UTC  }]    10.107.136.65 10.107.137.216 2019-03-05 03:00:17 +0000 UTC [] [{garo-test-xxx {nil nil &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:,Message:,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} {nil nil nil} false 0 /analytics/garo_xxx:latest docker-pullable:///analytics/garo_xxx@sha256:aba5fa93509510d50c6a93cf60a679389fe2e0f67c8fa9e50557e420a65645db docker://1ae2d1f2880b4352cc438caef9286a1a1c9b9a887fd492471c37ca31d4281d34}] BestEffort}) from podStatusChannel
I0305 04:03:11.425355    5193 config.go:303] Setting pods for source api
I0305 04:03:11.426725    5193 status_manager.go:476] Pod "garo-test-su67jxre2ia" (ce4cfb0f-3ef2-11e9-86fe-0ed827c0489e) does not exist on the server
I0305 04:03:11.427737    5193 kubelet.go:1847] SyncLoop (REMOVE, "api"): "garo-test-su67jxre2ia_azkaban(ce4cfb0f-3ef2-11e9-86fe-0ed827c0489e)"
I0305 04:03:11.427772    5193 config.go:100] Looking for [api], have seen map[api:{}]
I0305 04:03:11.427800    5193 kubelet.go:2041] Failed to delete pod "garo-test-su67jxre2ia_azkaban(ce4cfb0f-3ef2-11e9-86fe-0ed827c0489e)", err: pod not found
```

I don't have any idea what makes kubelet trigger that SyncLoop (DELETE, "api") process, but the timing definitively matches what Felix does when it deletes the conntrack entries.

The pods are scheduled by a simple "kubectl create" command which is executed from a simple cron-type system (azkaban, or just from command line). The pods are left to the apiserver after they have completed and a separated process cleans up old pods (just executes kubectl delete pod after one hour or so). So there shouldn't be any weird bindings or relations between the different pods, nor between a controller and the pods.

> If you're able to track down one of these "zombie" pods that Felix thinks is real but has long-since completed, that'd be useful. Does it still appear in the kubectl get pod output? What state is it in?

I'm not sure if this is the case in all of them, but at least in some of the cases the previous pod still exists in the api server in the Completed-state. Here are some of the relevant parts from an example kubectl get pod data from the pod which name comes up when Felix destroys the conntrack entries. This was taken a few seconds after the container execution was finished, a long (over 30 minutes) before the conntrack entries are cleared.
```
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": { ...  },
    "spec": {
        "containers": [
            {
                "args": [ ...  ],
                "command": [ ...     ],
                "env": [ ....      ],
                "image": "...",
                "imagePullPolicy": "Always",
                "name": "garo-test-...",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "nodeName": "ip-10-107-136-65.ec2.internal",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2019-03-05T03:00:17Z",
                "reason": "PodCompleted",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2019-03-05T03:01:20Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": null,
                "reason": "PodCompleted",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2019-03-05T03:00:17Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "docker://....",
                "image": "...",
                "imageID": "docker-pullable:///...",
                "lastState": {},
                "name": "garo-test-marketing-analytics-flows",
                "ready": false,
                "restartCount": 0,
                "state": {
                    "terminated": {
                        "containerID": "docker://...",
                        "exitCode": 0,
                        "finishedAt": "2019-03-05T03:01:19Z",
                        "reason": "Completed",
                        "startedAt": "2019-03-05T03:00:18Z"
                    }
                }
            }
        ],
        "hostIP": "10.107.136.65",
        "phase": "Succeeded",
        "podIP": "10.107.137.216",
        "qosClass": "BestEffort",
        "startTime": "2019-03-05T03:00:17Z"
    }
```

**Comment by garo** [comment]
It seems that @fasaxc's fix has been backported to quay.io/calico/node:v3.1.5-1-gc43ea879 which I'm now going to deploy. I will run my test workloads over the weekend to verify that the bug does not appear anymore and will report back to this thread by closing the issue early next week.

**Comment by garo** [comment]
The patch has not yet landed into quay.io/calico/node:release-v3.1 and it doesn't seem to be in release-v3.2 nor release-v3.3 either (for which AWS EKS team is planning to give support in https://github.com/aws/amazon-vpc-cni-k8s/pull/232), so I cannot yet start verifying this.

**Comment by garo** [comment]
I previously misunderstood that the release-v3.1 didn't contain the proposed patch for this, but I was mistaken. I also tried the very fresh quay.io/calico/node:v3.1.6 build with the typha:release-v3.1 image, but I am still experiencing this bug, so the patch https://github.com/projectcalico/libcalico-go/pull/1040 did not seem to have fixed this.

@fasaxc @caseydavenport any recommendation how to debug this further?

**Comment by fasaxc** [comment]
If you're using typha, it's actually typha that needs the fix.  Please can you try with typha from here: `quay.io/calico/node:v3.1.6`, I just checked and that does have the fix.  If that doesn't work, it's possible that the backport was incorrect somehow.

**Comment by fasaxc** [comment]
@garo confirmed that this appears to be fixed in typha v3.1.6.  @garo Please raise a fresh issue if you see new symptoms.  I'm confident that we've fixed _an_ issue here so if you see similar symptoms with that fix in place, please create a new issue.

**Comment by joinbestgo** [comment]
我在使用calico 3.17的版本中，也出现了楼主表述的类似问题，现在将版本换到calico 3.2.8问题已经得到解决，可能更换到其它的版本也有作用，但是我并没有去做更多的尝试
